// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v4.23.4
// source: src/protobufs.proto

package qmq

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LogLevelEnum int32

const (
	LogLevelEnum_LOG_LEVEL_UNSPECIFIED LogLevelEnum = 0
	LogLevelEnum_LOG_LEVEL_TRACE       LogLevelEnum = 1
	LogLevelEnum_LOG_LEVEL_DEBUG       LogLevelEnum = 2
	LogLevelEnum_LOG_LEVEL_ADVISE      LogLevelEnum = 3
	LogLevelEnum_LOG_LEVEL_WARN        LogLevelEnum = 4
	LogLevelEnum_LOG_LEVEL_ERROR       LogLevelEnum = 5
	LogLevelEnum_LOG_LEVEL_PANIC       LogLevelEnum = 6
)

// Enum value maps for LogLevelEnum.
var (
	LogLevelEnum_name = map[int32]string{
		0: "LOG_LEVEL_UNSPECIFIED",
		1: "LOG_LEVEL_TRACE",
		2: "LOG_LEVEL_DEBUG",
		3: "LOG_LEVEL_ADVISE",
		4: "LOG_LEVEL_WARN",
		5: "LOG_LEVEL_ERROR",
		6: "LOG_LEVEL_PANIC",
	}
	LogLevelEnum_value = map[string]int32{
		"LOG_LEVEL_UNSPECIFIED": 0,
		"LOG_LEVEL_TRACE":       1,
		"LOG_LEVEL_DEBUG":       2,
		"LOG_LEVEL_ADVISE":      3,
		"LOG_LEVEL_WARN":        4,
		"LOG_LEVEL_ERROR":       5,
		"LOG_LEVEL_PANIC":       6,
	}
)

func (x LogLevelEnum) Enum() *LogLevelEnum {
	p := new(LogLevelEnum)
	*p = x
	return p
}

func (x LogLevelEnum) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LogLevelEnum) Descriptor() protoreflect.EnumDescriptor {
	return file_src_protobufs_proto_enumTypes[0].Descriptor()
}

func (LogLevelEnum) Type() protoreflect.EnumType {
	return &file_src_protobufs_proto_enumTypes[0]
}

func (x LogLevelEnum) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LogLevelEnum.Descriptor instead.
func (LogLevelEnum) EnumDescriptor() ([]byte, []int) {
	return file_src_protobufs_proto_rawDescGZIP(), []int{0}
}

type ConnectionStateEnum int32

const (
	ConnectionStateEnum_CONNECTION_STATE_UNSPECIFIED  ConnectionStateEnum = 0
	ConnectionStateEnum_CONNECTION_STATE_CONNECTED    ConnectionStateEnum = 1
	ConnectionStateEnum_CONNECTION_STATE_DISCONNECTED ConnectionStateEnum = 2
)

// Enum value maps for ConnectionStateEnum.
var (
	ConnectionStateEnum_name = map[int32]string{
		0: "CONNECTION_STATE_UNSPECIFIED",
		1: "CONNECTION_STATE_CONNECTED",
		2: "CONNECTION_STATE_DISCONNECTED",
	}
	ConnectionStateEnum_value = map[string]int32{
		"CONNECTION_STATE_UNSPECIFIED":  0,
		"CONNECTION_STATE_CONNECTED":    1,
		"CONNECTION_STATE_DISCONNECTED": 2,
	}
)

func (x ConnectionStateEnum) Enum() *ConnectionStateEnum {
	p := new(ConnectionStateEnum)
	*p = x
	return p
}

func (x ConnectionStateEnum) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ConnectionStateEnum) Descriptor() protoreflect.EnumDescriptor {
	return file_src_protobufs_proto_enumTypes[1].Descriptor()
}

func (ConnectionStateEnum) Type() protoreflect.EnumType {
	return &file_src_protobufs_proto_enumTypes[1]
}

func (x ConnectionStateEnum) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ConnectionStateEnum.Descriptor instead.
func (ConnectionStateEnum) EnumDescriptor() ([]byte, []int) {
	return file_src_protobufs_proto_rawDescGZIP(), []int{1}
}

type GarageDoorStateEnum int32

const (
	GarageDoorStateEnum_GARAGE_DOOR_STATE_UNSPECIFIED GarageDoorStateEnum = 0
	GarageDoorStateEnum_GARAGE_DOOR_STATE_OPEN        GarageDoorStateEnum = 1
	GarageDoorStateEnum_GARAGE_DOOR_STATE_CLOSED      GarageDoorStateEnum = 2
)

// Enum value maps for GarageDoorStateEnum.
var (
	GarageDoorStateEnum_name = map[int32]string{
		0: "GARAGE_DOOR_STATE_UNSPECIFIED",
		1: "GARAGE_DOOR_STATE_OPEN",
		2: "GARAGE_DOOR_STATE_CLOSED",
	}
	GarageDoorStateEnum_value = map[string]int32{
		"GARAGE_DOOR_STATE_UNSPECIFIED": 0,
		"GARAGE_DOOR_STATE_OPEN":        1,
		"GARAGE_DOOR_STATE_CLOSED":      2,
	}
)

func (x GarageDoorStateEnum) Enum() *GarageDoorStateEnum {
	p := new(GarageDoorStateEnum)
	*p = x
	return p
}

func (x GarageDoorStateEnum) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GarageDoorStateEnum) Descriptor() protoreflect.EnumDescriptor {
	return file_src_protobufs_proto_enumTypes[2].Descriptor()
}

func (GarageDoorStateEnum) Type() protoreflect.EnumType {
	return &file_src_protobufs_proto_enumTypes[2]
}

func (x GarageDoorStateEnum) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GarageDoorStateEnum.Descriptor instead.
func (GarageDoorStateEnum) EnumDescriptor() ([]byte, []int) {
	return file_src_protobufs_proto_rawDescGZIP(), []int{2}
}

type WebServiceMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Content *anypb.Any `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
}

func (x *WebServiceMessage) Reset() {
	*x = WebServiceMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_protobufs_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WebServiceMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebServiceMessage) ProtoMessage() {}

func (x *WebServiceMessage) ProtoReflect() protoreflect.Message {
	mi := &file_src_protobufs_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebServiceMessage.ProtoReflect.Descriptor instead.
func (*WebServiceMessage) Descriptor() ([]byte, []int) {
	return file_src_protobufs_proto_rawDescGZIP(), []int{0}
}

func (x *WebServiceMessage) GetContent() *anypb.Any {
	if x != nil {
		return x.Content
	}
	return nil
}

type WebServiceGetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *WebServiceGetRequest) Reset() {
	*x = WebServiceGetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_protobufs_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WebServiceGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebServiceGetRequest) ProtoMessage() {}

func (x *WebServiceGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_protobufs_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebServiceGetRequest.ProtoReflect.Descriptor instead.
func (*WebServiceGetRequest) Descriptor() ([]byte, []int) {
	return file_src_protobufs_proto_rawDescGZIP(), []int{1}
}

func (x *WebServiceGetRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type WebServiceGetResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   string     `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value *anypb.Any `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *WebServiceGetResponse) Reset() {
	*x = WebServiceGetResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_protobufs_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WebServiceGetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebServiceGetResponse) ProtoMessage() {}

func (x *WebServiceGetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_src_protobufs_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebServiceGetResponse.ProtoReflect.Descriptor instead.
func (*WebServiceGetResponse) Descriptor() ([]byte, []int) {
	return file_src_protobufs_proto_rawDescGZIP(), []int{2}
}

func (x *WebServiceGetResponse) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *WebServiceGetResponse) GetValue() *anypb.Any {
	if x != nil {
		return x.Value
	}
	return nil
}

type WebServiceNotification struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   string     `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value *anypb.Any `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *WebServiceNotification) Reset() {
	*x = WebServiceNotification{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_protobufs_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WebServiceNotification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebServiceNotification) ProtoMessage() {}

func (x *WebServiceNotification) ProtoReflect() protoreflect.Message {
	mi := &file_src_protobufs_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebServiceNotification.ProtoReflect.Descriptor instead.
func (*WebServiceNotification) Descriptor() ([]byte, []int) {
	return file_src_protobufs_proto_rawDescGZIP(), []int{3}
}

func (x *WebServiceNotification) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *WebServiceNotification) GetValue() *anypb.Any {
	if x != nil {
		return x.Value
	}
	return nil
}

type WebServiceSetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   string     `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value *anypb.Any `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *WebServiceSetRequest) Reset() {
	*x = WebServiceSetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_protobufs_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WebServiceSetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebServiceSetRequest) ProtoMessage() {}

func (x *WebServiceSetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_protobufs_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebServiceSetRequest.ProtoReflect.Descriptor instead.
func (*WebServiceSetRequest) Descriptor() ([]byte, []int) {
	return file_src_protobufs_proto_rawDescGZIP(), []int{4}
}

func (x *WebServiceSetRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *WebServiceSetRequest) GetValue() *anypb.Any {
	if x != nil {
		return x.Value
	}
	return nil
}

type WebServiceSetResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *WebServiceSetResponse) Reset() {
	*x = WebServiceSetResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_protobufs_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WebServiceSetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebServiceSetResponse) ProtoMessage() {}

func (x *WebServiceSetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_src_protobufs_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebServiceSetResponse.ProtoReflect.Descriptor instead.
func (*WebServiceSetResponse) Descriptor() ([]byte, []int) {
	return file_src_protobufs_proto_rawDescGZIP(), []int{5}
}

type Data struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data      *anypb.Any             `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Writer    string                 `protobuf:"bytes,2,opt,name=writer,proto3" json:"writer,omitempty"`
	Writetime *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=writetime,proto3" json:"writetime,omitempty"`
}

func (x *Data) Reset() {
	*x = Data{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_protobufs_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data) ProtoMessage() {}

func (x *Data) ProtoReflect() protoreflect.Message {
	mi := &file_src_protobufs_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data.ProtoReflect.Descriptor instead.
func (*Data) Descriptor() ([]byte, []int) {
	return file_src_protobufs_proto_rawDescGZIP(), []int{6}
}

func (x *Data) GetData() *anypb.Any {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Data) GetWriter() string {
	if x != nil {
		return x.Writer
	}
	return ""
}

func (x *Data) GetWritetime() *timestamppb.Timestamp {
	if x != nil {
		return x.Writetime
	}
	return nil
}

type Int struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value int64 `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *Int) Reset() {
	*x = Int{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_protobufs_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Int) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Int) ProtoMessage() {}

func (x *Int) ProtoReflect() protoreflect.Message {
	mi := &file_src_protobufs_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Int.ProtoReflect.Descriptor instead.
func (*Int) Descriptor() ([]byte, []int) {
	return file_src_protobufs_proto_rawDescGZIP(), []int{7}
}

func (x *Int) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

type String struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value string `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *String) Reset() {
	*x = String{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_protobufs_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *String) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*String) ProtoMessage() {}

func (x *String) ProtoReflect() protoreflect.Message {
	mi := &file_src_protobufs_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use String.ProtoReflect.Descriptor instead.
func (*String) Descriptor() ([]byte, []int) {
	return file_src_protobufs_proto_rawDescGZIP(), []int{8}
}

func (x *String) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type Timestamp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *Timestamp) Reset() {
	*x = Timestamp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_protobufs_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Timestamp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Timestamp) ProtoMessage() {}

func (x *Timestamp) ProtoReflect() protoreflect.Message {
	mi := &file_src_protobufs_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Timestamp.ProtoReflect.Descriptor instead.
func (*Timestamp) Descriptor() ([]byte, []int) {
	return file_src_protobufs_proto_rawDescGZIP(), []int{9}
}

func (x *Timestamp) GetValue() *timestamppb.Timestamp {
	if x != nil {
		return x.Value
	}
	return nil
}

type Float struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value float64 `protobuf:"fixed64,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *Float) Reset() {
	*x = Float{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_protobufs_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Float) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Float) ProtoMessage() {}

func (x *Float) ProtoReflect() protoreflect.Message {
	mi := &file_src_protobufs_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Float.ProtoReflect.Descriptor instead.
func (*Float) Descriptor() ([]byte, []int) {
	return file_src_protobufs_proto_rawDescGZIP(), []int{10}
}

func (x *Float) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

type Bool struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value bool `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *Bool) Reset() {
	*x = Bool{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_protobufs_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Bool) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bool) ProtoMessage() {}

func (x *Bool) ProtoReflect() protoreflect.Message {
	mi := &file_src_protobufs_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bool.ProtoReflect.Descriptor instead.
func (*Bool) Descriptor() ([]byte, []int) {
	return file_src_protobufs_proto_rawDescGZIP(), []int{11}
}

func (x *Bool) GetValue() bool {
	if x != nil {
		return x.Value
	}
	return false
}

type Log struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Application string                 `protobuf:"bytes,1,opt,name=application,proto3" json:"application,omitempty"`
	Level       LogLevelEnum        `protobuf:"varint,2,opt,name=level,proto3,enum=qmq.LogLevelEnum" json:"level,omitempty"`
	Message     string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Timestamp   *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
}

func (x *Log) Reset() {
	*x = Log{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_protobufs_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Log) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Log) ProtoMessage() {}

func (x *Log) ProtoReflect() protoreflect.Message {
	mi := &file_src_protobufs_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Log.ProtoReflect.Descriptor instead.
func (*Log) Descriptor() ([]byte, []int) {
	return file_src_protobufs_proto_rawDescGZIP(), []int{12}
}

func (x *Log) GetApplication() string {
	if x != nil {
		return x.Application
	}
	return ""
}

func (x *Log) GetLevel() LogLevelEnum {
	if x != nil {
		return x.Level
	}
	return LogLevelEnum_LOG_LEVEL_UNSPECIFIED
}

func (x *Log) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Log) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type StreamContext struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LastConsumedId string `protobuf:"bytes,1,opt,name=last_consumed_id,json=lastConsumedId,proto3" json:"last_consumed_id,omitempty"`
	LastProducedId string `protobuf:"bytes,2,opt,name=last_produced_id,json=lastProducedId,proto3" json:"last_produced_id,omitempty"`
	TotalConsumed  int64  `protobuf:"varint,3,opt,name=total_consumed,json=totalConsumed,proto3" json:"total_consumed,omitempty"`
	TotalProduced  int64  `protobuf:"varint,4,opt,name=total_produced,json=totalProduced,proto3" json:"total_produced,omitempty"`
}

func (x *StreamContext) Reset() {
	*x = StreamContext{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_protobufs_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StreamContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamContext) ProtoMessage() {}

func (x *StreamContext) ProtoReflect() protoreflect.Message {
	mi := &file_src_protobufs_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamContext.ProtoReflect.Descriptor instead.
func (*StreamContext) Descriptor() ([]byte, []int) {
	return file_src_protobufs_proto_rawDescGZIP(), []int{13}
}

func (x *StreamContext) GetLastConsumedId() string {
	if x != nil {
		return x.LastConsumedId
	}
	return ""
}

func (x *StreamContext) GetLastProducedId() string {
	if x != nil {
		return x.LastProducedId
	}
	return ""
}

func (x *StreamContext) GetTotalConsumed() int64 {
	if x != nil {
		return x.TotalConsumed
	}
	return 0
}

func (x *StreamContext) GetTotalProduced() int64 {
	if x != nil {
		return x.TotalProduced
	}
	return 0
}

type Prayer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Time *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=time,proto3" json:"time,omitempty"`
}

func (x *Prayer) Reset() {
	*x = Prayer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_protobufs_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Prayer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Prayer) ProtoMessage() {}

func (x *Prayer) ProtoReflect() protoreflect.Message {
	mi := &file_src_protobufs_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Prayer.ProtoReflect.Descriptor instead.
func (*Prayer) Descriptor() ([]byte, []int) {
	return file_src_protobufs_proto_rawDescGZIP(), []int{14}
}

func (x *Prayer) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Prayer) GetTime() *timestamppb.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

type AudioRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Filename string `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
}

func (x *AudioRequest) Reset() {
	*x = AudioRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_protobufs_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AudioRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AudioRequest) ProtoMessage() {}

func (x *AudioRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_protobufs_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AudioRequest.ProtoReflect.Descriptor instead.
func (*AudioRequest) Descriptor() ([]byte, []int) {
	return file_src_protobufs_proto_rawDescGZIP(), []int{15}
}

func (x *AudioRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

type QMQTextToSpeechRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Text string `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
}

func (x *QMQTextToSpeechRequest) Reset() {
	*x = QMQTextToSpeechRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_protobufs_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QMQTextToSpeechRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QMQTextToSpeechRequest) ProtoMessage() {}

func (x *QMQTextToSpeechRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_protobufs_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QMQTextToSpeechRequest.ProtoReflect.Descriptor instead.
func (*QMQTextToSpeechRequest) Descriptor() ([]byte, []int) {
	return file_src_protobufs_proto_rawDescGZIP(), []int{16}
}

func (x *QMQTextToSpeechRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type MqttMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Qos       int32  `protobuf:"varint,2,opt,name=qos,proto3" json:"qos,omitempty"`
	Topic     string `protobuf:"bytes,3,opt,name=topic,proto3" json:"topic,omitempty"`
	Payload   []byte `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	Retained  bool   `protobuf:"varint,5,opt,name=retained,proto3" json:"retained,omitempty"`
	Duplicate bool   `protobuf:"varint,6,opt,name=duplicate,proto3" json:"duplicate,omitempty"`
}

func (x *MqttMessage) Reset() {
	*x = MqttMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_protobufs_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MqttMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MqttMessage) ProtoMessage() {}

func (x *QMQMqttMessage) ProtoReflect() protoreflect.Message {
	mi := &file_src_protobufs_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QMQMqttMessage.ProtoReflect.Descriptor instead.
func (*QMQMqttMessage) Descriptor() ([]byte, []int) {
	return file_src_protobufs_proto_rawDescGZIP(), []int{16}
}

func (x *MqttMessage) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *MqttMessage) GetQos() int32 {
	if x != nil {
		return x.Qos
	}
	return 0
}

func (x *MqttMessage) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *MqttMessage) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *MqttMessage) GetRetained() bool {
	if x != nil {
		return x.Retained
	}
	return false
}

func (x *MqttMessage) GetDuplicate() bool {
	if x != nil {
		return x.Duplicate
	}
	return false
}

type GarageDoorState struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value GarageDoorStateEnum `protobuf:"varint,1,opt,name=value,proto3,enum=qmq.GarageDoorStateEnum" json:"value,omitempty"`
}

func (x *GarageDoorState) Reset() {
	*x = GarageDoorState{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_protobufs_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GarageDoorState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GarageDoorState) ProtoMessage() {}

func (x *QMQGarageDoorState) ProtoReflect() protoreflect.Message {
	mi := &file_src_protobufs_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QMQGarageDoorState.ProtoReflect.Descriptor instead.
func (*QMQGarageDoorState) Descriptor() ([]byte, []int) {
	return file_src_protobufs_proto_rawDescGZIP(), []int{17}
}

func (x *GarageDoorState) GetValue() GarageDoorStateEnum {
	if x != nil {
		return x.Value
	}
	return GarageDoorStateEnum_GARAGE_DOOR_STATE_UNSPECIFIED
}

type ConnectionState struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value ConnectionStateEnum `protobuf:"varint,1,opt,name=value,proto3,enum=qmq.ConnectionStateEnum" json:"value,omitempty"`
}

func (x *ConnectionState) Reset() {
	*x = ConnectionState{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_protobufs_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConnectionState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectionState) ProtoMessage() {}

func (x *QMQConnectionState) ProtoReflect() protoreflect.Message {
	mi := &file_src_protobufs_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QMQConnectionState.ProtoReflect.Descriptor instead.
func (*QMQConnectionState) Descriptor() ([]byte, []int) {
	return file_src_protobufs_proto_rawDescGZIP(), []int{18}
}

func (x *ConnectionState) GetValue() ConnectionStateEnum {
	if x != nil {
		return x.Value
	}
	return ConnectionStateEnum_CONNECTION_STATE_UNSPECIFIED
}

var File_src_protobufs_proto protoreflect.FileDescriptor

var file_src_protobufs_proto_rawDesc = []byte{
	0x0a, 0x13, 0x73, 0x72, 0x63, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x73, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x71, 0x6d, 0x71, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65,
	0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x19, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x61, 0x6e, 0x79,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x46, 0x0a, 0x14, 0x51, 0x4d, 0x51, 0x57, 0x65, 0x62,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x2e,
	0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x14, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2e, 0x41, 0x6e, 0x79, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x22, 0x2b,
	0x0a, 0x17, 0x51, 0x4d, 0x51, 0x57, 0x65, 0x62, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x47,
	0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x22, 0x58, 0x0a, 0x18, 0x51,
	0x4d, 0x51, 0x57, 0x65, 0x62, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x47, 0x65, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x2a, 0x0a, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x41, 0x6e, 0x79, 0x52, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x59, 0x0a, 0x19, 0x51, 0x4d, 0x51, 0x57, 0x65, 0x62, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x6b, 0x65, 0x79, 0x12, 0x2a, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x41, 0x6e, 0x79, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x22, 0x57, 0x0a, 0x17, 0x51, 0x4d, 0x51, 0x57, 0x65, 0x62, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x53, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6b,
	0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x2a, 0x0a,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x41,
	0x6e, 0x79, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x1a, 0x0a, 0x18, 0x51, 0x4d, 0x51,
	0x57, 0x65, 0x62, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x53, 0x65, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x85, 0x01, 0x0a, 0x07, 0x51, 0x4d, 0x51, 0x44, 0x61, 0x74,
	0x61, 0x12, 0x28, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x14, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2e, 0x41, 0x6e, 0x79, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x16, 0x0a, 0x06, 0x77,
	0x72, 0x69, 0x74, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x77, 0x72, 0x69,
	0x74, 0x65, 0x72, 0x12, 0x38, 0x0a, 0x09, 0x77, 0x72, 0x69, 0x74, 0x65, 0x74, 0x69, 0x6d, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x52, 0x09, 0x77, 0x72, 0x69, 0x74, 0x65, 0x74, 0x69, 0x6d, 0x65, 0x22, 0x1e, 0x0a,
	0x06, 0x51, 0x4d, 0x51, 0x49, 0x6e, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x21, 0x0a,
	0x09, 0x51, 0x4d, 0x51, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x22, 0x40, 0x0a, 0x0c, 0x51, 0x4d, 0x51, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x12, 0x30, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x22, 0x20, 0x0a, 0x08, 0x51, 0x4d, 0x51, 0x46, 0x6c, 0x6f, 0x61, 0x74, 0x12, 0x14,
	0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x22, 0x1f, 0x0a, 0x07, 0x51, 0x4d, 0x51, 0x42, 0x6f, 0x6f, 0x6c, 0x12,
	0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0xaa, 0x01, 0x0a, 0x06, 0x51, 0x4d, 0x51, 0x4c, 0x6f, 0x67,
	0x12, 0x20, 0x0a, 0x0b, 0x61, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x61, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x2a, 0x0a, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x14, 0x2e, 0x71, 0x6d, 0x71, 0x2e, 0x51, 0x4d, 0x51, 0x4c, 0x6f, 0x67, 0x4c, 0x65,
	0x76, 0x65, 0x6c, 0x45, 0x6e, 0x75, 0x6d, 0x52, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x12, 0x18,
	0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x38, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65,
	0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x22, 0xb4, 0x01, 0x0a, 0x10, 0x51, 0x4d, 0x51, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d,
	0x43, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x12, 0x28, 0x0a, 0x10, 0x6c, 0x61, 0x73, 0x74, 0x5f,
	0x63, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65, 0x64, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0e, 0x6c, 0x61, 0x73, 0x74, 0x43, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65, 0x64, 0x49,
	0x64, 0x12, 0x28, 0x0a, 0x10, 0x6c, 0x61, 0x73, 0x74, 0x5f, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63,
	0x65, 0x64, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x6c, 0x61, 0x73,
	0x74, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x65, 0x64, 0x49, 0x64, 0x12, 0x25, 0x0a, 0x0e, 0x74,
	0x6f, 0x74, 0x61, 0x6c, 0x5f, 0x63, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65, 0x64, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x0d, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x43, 0x6f, 0x6e, 0x73, 0x75, 0x6d,
	0x65, 0x64, 0x12, 0x25, 0x0a, 0x0e, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x5f, 0x70, 0x72, 0x6f, 0x64,
	0x75, 0x63, 0x65, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0d, 0x74, 0x6f, 0x74, 0x61,
	0x6c, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x65, 0x64, 0x22, 0x4f, 0x0a, 0x09, 0x51, 0x4d, 0x51,
	0x50, 0x72, 0x61, 0x79, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x2e, 0x0a, 0x04, 0x74, 0x69,
	0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73,
	0x74, 0x61, 0x6d, 0x70, 0x52, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x22, 0x2d, 0x0a, 0x0f, 0x51, 0x4d,
	0x51, 0x41, 0x75, 0x64, 0x69, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a,
	0x08, 0x66, 0x69, 0x6c, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x66, 0x69, 0x6c, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x2c, 0x0a, 0x16, 0x51, 0x4d, 0x51,
	0x54, 0x65, 0x78, 0x74, 0x54, 0x6f, 0x53, 0x70, 0x65, 0x65, 0x63, 0x68, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x65, 0x78, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x74, 0x65, 0x78, 0x74, 0x22, 0x9c, 0x01, 0x0a, 0x0e, 0x51, 0x4d, 0x51, 0x4d,
	0x71, 0x74, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x71, 0x6f,
	0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x71, 0x6f, 0x73, 0x12, 0x14, 0x0a, 0x05,
	0x74, 0x6f, 0x70, 0x69, 0x63, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x70,
	0x69, 0x63, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x1a, 0x0a, 0x08,
	0x72, 0x65, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08,
	0x72, 0x65, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x64, 0x75, 0x70, 0x6c,
	0x69, 0x63, 0x61, 0x74, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x64, 0x75, 0x70,
	0x6c, 0x69, 0x63, 0x61, 0x74, 0x65, 0x22, 0x47, 0x0a, 0x12, 0x51, 0x4d, 0x51, 0x47, 0x61, 0x72,
	0x61, 0x67, 0x65, 0x44, 0x6f, 0x6f, 0x72, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x31, 0x0a, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1b, 0x2e, 0x71, 0x6d,
	0x71, 0x2e, 0x51, 0x4d, 0x51, 0x47, 0x61, 0x72, 0x61, 0x67, 0x65, 0x44, 0x6f, 0x6f, 0x72, 0x53,
	0x74, 0x61, 0x74, 0x65, 0x45, 0x6e, 0x75, 0x6d, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22,
	0x47, 0x0a, 0x12, 0x51, 0x4d, 0x51, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x31, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x1b, 0x2e, 0x71, 0x6d, 0x71, 0x2e, 0x51, 0x4d, 0x51, 0x43, 0x6f,
	0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x65, 0x45, 0x6e, 0x75,
	0x6d, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x2a, 0xaa, 0x01, 0x0a, 0x0f, 0x51, 0x4d, 0x51,
	0x4c, 0x6f, 0x67, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x45, 0x6e, 0x75, 0x6d, 0x12, 0x19, 0x0a, 0x15,
	0x4c, 0x4f, 0x47, 0x5f, 0x4c, 0x45, 0x56, 0x45, 0x4c, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43,
	0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x13, 0x0a, 0x0f, 0x4c, 0x4f, 0x47, 0x5f, 0x4c,
	0x45, 0x56, 0x45, 0x4c, 0x5f, 0x54, 0x52, 0x41, 0x43, 0x45, 0x10, 0x01, 0x12, 0x13, 0x0a, 0x0f,
	0x4c, 0x4f, 0x47, 0x5f, 0x4c, 0x45, 0x56, 0x45, 0x4c, 0x5f, 0x44, 0x45, 0x42, 0x55, 0x47, 0x10,
	0x02, 0x12, 0x14, 0x0a, 0x10, 0x4c, 0x4f, 0x47, 0x5f, 0x4c, 0x45, 0x56, 0x45, 0x4c, 0x5f, 0x41,
	0x44, 0x56, 0x49, 0x53, 0x45, 0x10, 0x03, 0x12, 0x12, 0x0a, 0x0e, 0x4c, 0x4f, 0x47, 0x5f, 0x4c,
	0x45, 0x56, 0x45, 0x4c, 0x5f, 0x57, 0x41, 0x52, 0x4e, 0x10, 0x04, 0x12, 0x13, 0x0a, 0x0f, 0x4c,
	0x4f, 0x47, 0x5f, 0x4c, 0x45, 0x56, 0x45, 0x4c, 0x5f, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x05,
	0x12, 0x13, 0x0a, 0x0f, 0x4c, 0x4f, 0x47, 0x5f, 0x4c, 0x45, 0x56, 0x45, 0x4c, 0x5f, 0x50, 0x41,
	0x4e, 0x49, 0x43, 0x10, 0x06, 0x2a, 0x7d, 0x0a, 0x16, 0x51, 0x4d, 0x51, 0x43, 0x6f, 0x6e, 0x6e,
	0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x65, 0x45, 0x6e, 0x75, 0x6d, 0x12,
	0x20, 0x0a, 0x1c, 0x43, 0x4f, 0x4e, 0x4e, 0x45, 0x43, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x53, 0x54,
	0x41, 0x54, 0x45, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10,
	0x00, 0x12, 0x1e, 0x0a, 0x1a, 0x43, 0x4f, 0x4e, 0x4e, 0x45, 0x43, 0x54, 0x49, 0x4f, 0x4e, 0x5f,
	0x53, 0x54, 0x41, 0x54, 0x45, 0x5f, 0x43, 0x4f, 0x4e, 0x4e, 0x45, 0x43, 0x54, 0x45, 0x44, 0x10,
	0x01, 0x12, 0x21, 0x0a, 0x1d, 0x43, 0x4f, 0x4e, 0x4e, 0x45, 0x43, 0x54, 0x49, 0x4f, 0x4e, 0x5f,
	0x53, 0x54, 0x41, 0x54, 0x45, 0x5f, 0x44, 0x49, 0x53, 0x43, 0x4f, 0x4e, 0x4e, 0x45, 0x43, 0x54,
	0x45, 0x44, 0x10, 0x02, 0x2a, 0x75, 0x0a, 0x16, 0x51, 0x4d, 0x51, 0x47, 0x61, 0x72, 0x61, 0x67,
	0x65, 0x44, 0x6f, 0x6f, 0x72, 0x53, 0x74, 0x61, 0x74, 0x65, 0x45, 0x6e, 0x75, 0x6d, 0x12, 0x21,
	0x0a, 0x1d, 0x47, 0x41, 0x52, 0x41, 0x47, 0x45, 0x5f, 0x44, 0x4f, 0x4f, 0x52, 0x5f, 0x53, 0x54,
	0x41, 0x54, 0x45, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10,
	0x00, 0x12, 0x1a, 0x0a, 0x16, 0x47, 0x41, 0x52, 0x41, 0x47, 0x45, 0x5f, 0x44, 0x4f, 0x4f, 0x52,
	0x5f, 0x53, 0x54, 0x41, 0x54, 0x45, 0x5f, 0x4f, 0x50, 0x45, 0x4e, 0x10, 0x01, 0x12, 0x1c, 0x0a,
	0x18, 0x47, 0x41, 0x52, 0x41, 0x47, 0x45, 0x5f, 0x44, 0x4f, 0x4f, 0x52, 0x5f, 0x53, 0x54, 0x41,
	0x54, 0x45, 0x5f, 0x43, 0x4c, 0x4f, 0x53, 0x45, 0x44, 0x10, 0x02, 0x42, 0x09, 0x5a, 0x07, 0x71,
	0x6d, 0x71, 0x2f, 0x71, 0x6d, 0x71, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_src_protobufs_proto_rawDescOnce sync.Once
	file_src_protobufs_proto_rawDescData = file_src_protobufs_proto_rawDesc
)

func file_src_protobufs_proto_rawDescGZIP() []byte {
	file_src_protobufs_proto_rawDescOnce.Do(func() {
		file_src_protobufs_proto_rawDescData = protoimpl.X.CompressGZIP(file_src_protobufs_proto_rawDescData)
	})
	return file_src_protobufs_proto_rawDescData
}

var file_src_protobufs_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_src_protobufs_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_src_protobufs_proto_goTypes = []interface{}{
	(QMQLogLevelEnum)(0),              // 0: qmq.QMQLogLevelEnum
	(QMQConnectionStateEnum)(0),       // 1: qmq.QMQConnectionStateEnum
	(QMQGarageDoorStateEnum)(0),       // 2: qmq.QMQGarageDoorStateEnum
	(*QMQWebServiceMessage)(nil),      // 3: qmq.QMQWebServiceMessage
	(*QMQWebServiceGetRequest)(nil),   // 4: qmq.QMQWebServiceGetRequest
	(*QMQWebServiceGetResponse)(nil),  // 5: qmq.QMQWebServiceGetResponse
	(*QMQWebServiceNotification)(nil), // 6: qmq.QMQWebServiceNotification
	(*QMQWebServiceSetRequest)(nil),   // 7: qmq.QMQWebServiceSetRequest
	(*QMQWebServiceSetResponse)(nil),  // 8: qmq.QMQWebServiceSetResponse
	(*QMQData)(nil),                   // 9: qmq.QMQData
	(*QMQInt)(nil),                    // 10: qmq.QMQInt
	(*QMQString)(nil),                 // 11: qmq.QMQString
	(*QMQTimestamp)(nil),              // 12: qmq.QMQTimestamp
	(*QMQFloat)(nil),                  // 13: qmq.QMQFloat
	(*QMQBool)(nil),                   // 14: qmq.QMQBool
	(*QMQLog)(nil),                    // 15: qmq.QMQLog
	(*QMQStreamContext)(nil),          // 16: qmq.QMQStreamContext
	(*QMQPrayer)(nil),                 // 17: qmq.QMQPrayer
	(*QMQAudioRequest)(nil),           // 18: qmq.QMQAudioRequest
	(*QMQMqttMessage)(nil),            // 19: qmq.QMQMqttMessage
	(*QMQGarageDoorState)(nil),        // 20: qmq.QMQGarageDoorState
	(*QMQConnectionState)(nil),        // 21: qmq.QMQConnectionState
	(*anypb.Any)(nil),                 // 22: google.protobuf.Any
	(*timestamppb.Timestamp)(nil),     // 23: google.protobuf.Timestamp
}
var file_src_protobufs_proto_depIdxs = []int32{
	22, // 0: qmq.QMQWebServiceMessage.content:type_name -> google.protobuf.Any
	22, // 1: qmq.QMQWebServiceGetResponse.value:type_name -> google.protobuf.Any
	22, // 2: qmq.QMQWebServiceNotification.value:type_name -> google.protobuf.Any
	22, // 3: qmq.QMQWebServiceSetRequest.value:type_name -> google.protobuf.Any
	22, // 4: qmq.QMQData.data:type_name -> google.protobuf.Any
	23, // 5: qmq.QMQData.writetime:type_name -> google.protobuf.Timestamp
	23, // 6: qmq.QMQTimestamp.value:type_name -> google.protobuf.Timestamp
	0,  // 7: qmq.QMQLog.level:type_name -> qmq.QMQLogLevelEnum
	23, // 8: qmq.QMQLog.timestamp:type_name -> google.protobuf.Timestamp
	23, // 9: qmq.QMQPrayer.time:type_name -> google.protobuf.Timestamp
	2,  // 10: qmq.QMQGarageDoorState.value:type_name -> qmq.QMQGarageDoorStateEnum
	1,  // 11: qmq.QMQConnectionState.value:type_name -> qmq.QMQConnectionStateEnum
	12, // [12:12] is the sub-list for method output_type
	12, // [12:12] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_src_protobufs_proto_init() }
func file_src_protobufs_proto_init() {
	if File_src_protobufs_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_src_protobufs_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WebServiceMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_protobufs_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WebServiceGetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_protobufs_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WebServiceGetResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_protobufs_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WebServiceNotification); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_protobufs_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WebServiceSetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_protobufs_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WebServiceSetResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_protobufs_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Data); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_protobufs_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Int); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_protobufs_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*String); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_protobufs_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Timestamp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_protobufs_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Float); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_protobufs_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Bool); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_protobufs_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Log); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_protobufs_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StreamContext); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_protobufs_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Prayer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_protobufs_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AudioRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_protobufs_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QMQMqttMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_protobufs_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QMQGarageDoorState); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_protobufs_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QMQConnectionState); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_src_protobufs_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_src_protobufs_proto_goTypes,
		DependencyIndexes: file_src_protobufs_proto_depIdxs,
		EnumInfos:         file_src_protobufs_proto_enumTypes,
		MessageInfos:      file_src_protobufs_proto_msgTypes,
	}.Build()
	File_src_protobufs_proto = out.File
	file_src_protobufs_proto_rawDesc = nil
	file_src_protobufs_proto_goTypes = nil
	file_src_protobufs_proto_depIdxs = nil
}
