// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v4.23.4
// source: src/protobufs.proto

package qmq

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type QMQLogLevelEnum int32

const (
	QMQLogLevelEnum_LOG_LEVEL_UNSPECIFIED QMQLogLevelEnum = 0
	QMQLogLevelEnum_LOG_LEVEL_TRACE       QMQLogLevelEnum = 1
	QMQLogLevelEnum_LOG_LEVEL_DEBUG       QMQLogLevelEnum = 2
	QMQLogLevelEnum_LOG_LEVEL_ADVISE      QMQLogLevelEnum = 3
	QMQLogLevelEnum_LOG_LEVEL_WARN        QMQLogLevelEnum = 4
	QMQLogLevelEnum_LOG_LEVEL_ERROR       QMQLogLevelEnum = 5
	QMQLogLevelEnum_LOG_LEVEL_PANIC       QMQLogLevelEnum = 6
)

// Enum value maps for QMQLogLevelEnum.
var (
	QMQLogLevelEnum_name = map[int32]string{
		0: "LOG_LEVEL_UNSPECIFIED",
		1: "LOG_LEVEL_TRACE",
		2: "LOG_LEVEL_DEBUG",
		3: "LOG_LEVEL_ADVISE",
		4: "LOG_LEVEL_WARN",
		5: "LOG_LEVEL_ERROR",
		6: "LOG_LEVEL_PANIC",
	}
	QMQLogLevelEnum_value = map[string]int32{
		"LOG_LEVEL_UNSPECIFIED": 0,
		"LOG_LEVEL_TRACE":       1,
		"LOG_LEVEL_DEBUG":       2,
		"LOG_LEVEL_ADVISE":      3,
		"LOG_LEVEL_WARN":        4,
		"LOG_LEVEL_ERROR":       5,
		"LOG_LEVEL_PANIC":       6,
	}
)

func (x QMQLogLevelEnum) Enum() *QMQLogLevelEnum {
	p := new(QMQLogLevelEnum)
	*p = x
	return p
}

func (x QMQLogLevelEnum) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (QMQLogLevelEnum) Descriptor() protoreflect.EnumDescriptor {
	return file_src_protobufs_proto_enumTypes[0].Descriptor()
}

func (QMQLogLevelEnum) Type() protoreflect.EnumType {
	return &file_src_protobufs_proto_enumTypes[0]
}

func (x QMQLogLevelEnum) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use QMQLogLevelEnum.Descriptor instead.
func (QMQLogLevelEnum) EnumDescriptor() ([]byte, []int) {
	return file_src_protobufs_proto_rawDescGZIP(), []int{0}
}

type QMQGarageDoorStateEnum int32

const (
	QMQGarageDoorStateEnum_GARAGE_DOOR_STATE_UNSPECIFIED QMQGarageDoorStateEnum = 0
	QMQGarageDoorStateEnum_GARAGE_DOOR_STATE_OPEN        QMQGarageDoorStateEnum = 1
	QMQGarageDoorStateEnum_GARAGE_DOOR_STATE_CLOSED      QMQGarageDoorStateEnum = 2
)

// Enum value maps for QMQGarageDoorStateEnum.
var (
	QMQGarageDoorStateEnum_name = map[int32]string{
		0: "GARAGE_DOOR_STATE_UNSPECIFIED",
		1: "GARAGE_DOOR_STATE_OPEN",
		2: "GARAGE_DOOR_STATE_CLOSED",
	}
	QMQGarageDoorStateEnum_value = map[string]int32{
		"GARAGE_DOOR_STATE_UNSPECIFIED": 0,
		"GARAGE_DOOR_STATE_OPEN":        1,
		"GARAGE_DOOR_STATE_CLOSED":      2,
	}
)

func (x QMQGarageDoorStateEnum) Enum() *QMQGarageDoorStateEnum {
	p := new(QMQGarageDoorStateEnum)
	*p = x
	return p
}

func (x QMQGarageDoorStateEnum) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (QMQGarageDoorStateEnum) Descriptor() protoreflect.EnumDescriptor {
	return file_src_protobufs_proto_enumTypes[1].Descriptor()
}

func (QMQGarageDoorStateEnum) Type() protoreflect.EnumType {
	return &file_src_protobufs_proto_enumTypes[1]
}

func (x QMQGarageDoorStateEnum) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use QMQGarageDoorStateEnum.Descriptor instead.
func (QMQGarageDoorStateEnum) EnumDescriptor() ([]byte, []int) {
	return file_src_protobufs_proto_rawDescGZIP(), []int{1}
}

type QMQData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data      *anypb.Any             `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Writer    string                 `protobuf:"bytes,2,opt,name=writer,proto3" json:"writer,omitempty"`
	Writetime *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=writetime,proto3" json:"writetime,omitempty"`
}

func (x *QMQData) Reset() {
	*x = QMQData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_protobufs_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QMQData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QMQData) ProtoMessage() {}

func (x *QMQData) ProtoReflect() protoreflect.Message {
	mi := &file_src_protobufs_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QMQData.ProtoReflect.Descriptor instead.
func (*QMQData) Descriptor() ([]byte, []int) {
	return file_src_protobufs_proto_rawDescGZIP(), []int{0}
}

func (x *QMQData) GetData() *anypb.Any {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *QMQData) GetWriter() string {
	if x != nil {
		return x.Writer
	}
	return ""
}

func (x *QMQData) GetWritetime() *timestamppb.Timestamp {
	if x != nil {
		return x.Writetime
	}
	return nil
}

type QMQInt struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value int64 `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *QMQInt) Reset() {
	*x = QMQInt{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_protobufs_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QMQInt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QMQInt) ProtoMessage() {}

func (x *QMQInt) ProtoReflect() protoreflect.Message {
	mi := &file_src_protobufs_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QMQInt.ProtoReflect.Descriptor instead.
func (*QMQInt) Descriptor() ([]byte, []int) {
	return file_src_protobufs_proto_rawDescGZIP(), []int{1}
}

func (x *QMQInt) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

type QMQString struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value string `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *QMQString) Reset() {
	*x = QMQString{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_protobufs_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QMQString) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QMQString) ProtoMessage() {}

func (x *QMQString) ProtoReflect() protoreflect.Message {
	mi := &file_src_protobufs_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QMQString.ProtoReflect.Descriptor instead.
func (*QMQString) Descriptor() ([]byte, []int) {
	return file_src_protobufs_proto_rawDescGZIP(), []int{2}
}

func (x *QMQString) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type QMQTimestamp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *QMQTimestamp) Reset() {
	*x = QMQTimestamp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_protobufs_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QMQTimestamp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QMQTimestamp) ProtoMessage() {}

func (x *QMQTimestamp) ProtoReflect() protoreflect.Message {
	mi := &file_src_protobufs_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QMQTimestamp.ProtoReflect.Descriptor instead.
func (*QMQTimestamp) Descriptor() ([]byte, []int) {
	return file_src_protobufs_proto_rawDescGZIP(), []int{3}
}

func (x *QMQTimestamp) GetValue() *timestamppb.Timestamp {
	if x != nil {
		return x.Value
	}
	return nil
}

type QMQFloat struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value float64 `protobuf:"fixed64,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *QMQFloat) Reset() {
	*x = QMQFloat{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_protobufs_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QMQFloat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QMQFloat) ProtoMessage() {}

func (x *QMQFloat) ProtoReflect() protoreflect.Message {
	mi := &file_src_protobufs_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QMQFloat.ProtoReflect.Descriptor instead.
func (*QMQFloat) Descriptor() ([]byte, []int) {
	return file_src_protobufs_proto_rawDescGZIP(), []int{4}
}

func (x *QMQFloat) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

type QMQBool struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value bool `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *QMQBool) Reset() {
	*x = QMQBool{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_protobufs_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QMQBool) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QMQBool) ProtoMessage() {}

func (x *QMQBool) ProtoReflect() protoreflect.Message {
	mi := &file_src_protobufs_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QMQBool.ProtoReflect.Descriptor instead.
func (*QMQBool) Descriptor() ([]byte, []int) {
	return file_src_protobufs_proto_rawDescGZIP(), []int{5}
}

func (x *QMQBool) GetValue() bool {
	if x != nil {
		return x.Value
	}
	return false
}

type QMQLog struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Application string                 `protobuf:"bytes,1,opt,name=application,proto3" json:"application,omitempty"`
	Level       QMQLogLevelEnum        `protobuf:"varint,2,opt,name=level,proto3,enum=qmq.QMQLogLevelEnum" json:"level,omitempty"`
	Message     string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Timestamp   *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
}

func (x *QMQLog) Reset() {
	*x = QMQLog{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_protobufs_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QMQLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QMQLog) ProtoMessage() {}

func (x *QMQLog) ProtoReflect() protoreflect.Message {
	mi := &file_src_protobufs_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QMQLog.ProtoReflect.Descriptor instead.
func (*QMQLog) Descriptor() ([]byte, []int) {
	return file_src_protobufs_proto_rawDescGZIP(), []int{6}
}

func (x *QMQLog) GetApplication() string {
	if x != nil {
		return x.Application
	}
	return ""
}

func (x *QMQLog) GetLevel() QMQLogLevelEnum {
	if x != nil {
		return x.Level
	}
	return QMQLogLevelEnum_LOG_LEVEL_UNSPECIFIED
}

func (x *QMQLog) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *QMQLog) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type QMQStreamContext struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LastConsumedId string `protobuf:"bytes,1,opt,name=last_consumed_id,json=lastConsumedId,proto3" json:"last_consumed_id,omitempty"`
	LastProducedId string `protobuf:"bytes,2,opt,name=last_produced_id,json=lastProducedId,proto3" json:"last_produced_id,omitempty"`
	TotalConsumed  int64  `protobuf:"varint,3,opt,name=total_consumed,json=totalConsumed,proto3" json:"total_consumed,omitempty"`
	TotalProduced  int64  `protobuf:"varint,4,opt,name=total_produced,json=totalProduced,proto3" json:"total_produced,omitempty"`
}

func (x *QMQStreamContext) Reset() {
	*x = QMQStreamContext{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_protobufs_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QMQStreamContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QMQStreamContext) ProtoMessage() {}

func (x *QMQStreamContext) ProtoReflect() protoreflect.Message {
	mi := &file_src_protobufs_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QMQStreamContext.ProtoReflect.Descriptor instead.
func (*QMQStreamContext) Descriptor() ([]byte, []int) {
	return file_src_protobufs_proto_rawDescGZIP(), []int{7}
}

func (x *QMQStreamContext) GetLastConsumedId() string {
	if x != nil {
		return x.LastConsumedId
	}
	return ""
}

func (x *QMQStreamContext) GetLastProducedId() string {
	if x != nil {
		return x.LastProducedId
	}
	return ""
}

func (x *QMQStreamContext) GetTotalConsumed() int64 {
	if x != nil {
		return x.TotalConsumed
	}
	return 0
}

func (x *QMQStreamContext) GetTotalProduced() int64 {
	if x != nil {
		return x.TotalProduced
	}
	return 0
}

type QMQPrayer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Time *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=time,proto3" json:"time,omitempty"`
}

func (x *QMQPrayer) Reset() {
	*x = QMQPrayer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_protobufs_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QMQPrayer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QMQPrayer) ProtoMessage() {}

func (x *QMQPrayer) ProtoReflect() protoreflect.Message {
	mi := &file_src_protobufs_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QMQPrayer.ProtoReflect.Descriptor instead.
func (*QMQPrayer) Descriptor() ([]byte, []int) {
	return file_src_protobufs_proto_rawDescGZIP(), []int{8}
}

func (x *QMQPrayer) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *QMQPrayer) GetTime() *timestamppb.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

type QMQAudioRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Filename string `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
}

func (x *QMQAudioRequest) Reset() {
	*x = QMQAudioRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_protobufs_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QMQAudioRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QMQAudioRequest) ProtoMessage() {}

func (x *QMQAudioRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_protobufs_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QMQAudioRequest.ProtoReflect.Descriptor instead.
func (*QMQAudioRequest) Descriptor() ([]byte, []int) {
	return file_src_protobufs_proto_rawDescGZIP(), []int{9}
}

func (x *QMQAudioRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

type QMQMqttMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Qos       int32  `protobuf:"varint,2,opt,name=qos,proto3" json:"qos,omitempty"`
	Topic     string `protobuf:"bytes,3,opt,name=topic,proto3" json:"topic,omitempty"`
	Payload   []byte `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	Retained  bool   `protobuf:"varint,5,opt,name=retained,proto3" json:"retained,omitempty"`
	Duplicate bool   `protobuf:"varint,6,opt,name=duplicate,proto3" json:"duplicate,omitempty"`
}

func (x *QMQMqttMessage) Reset() {
	*x = QMQMqttMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_protobufs_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QMQMqttMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QMQMqttMessage) ProtoMessage() {}

func (x *QMQMqttMessage) ProtoReflect() protoreflect.Message {
	mi := &file_src_protobufs_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QMQMqttMessage.ProtoReflect.Descriptor instead.
func (*QMQMqttMessage) Descriptor() ([]byte, []int) {
	return file_src_protobufs_proto_rawDescGZIP(), []int{10}
}

func (x *QMQMqttMessage) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *QMQMqttMessage) GetQos() int32 {
	if x != nil {
		return x.Qos
	}
	return 0
}

func (x *QMQMqttMessage) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *QMQMqttMessage) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *QMQMqttMessage) GetRetained() bool {
	if x != nil {
		return x.Retained
	}
	return false
}

func (x *QMQMqttMessage) GetDuplicate() bool {
	if x != nil {
		return x.Duplicate
	}
	return false
}

var File_src_protobufs_proto protoreflect.FileDescriptor

var file_src_protobufs_proto_rawDesc = []byte{
	0x0a, 0x13, 0x73, 0x72, 0x63, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x73, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x71, 0x6d, 0x71, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65,
	0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x19, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x61, 0x6e, 0x79,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x85, 0x01, 0x0a, 0x07, 0x51, 0x4d, 0x51, 0x44, 0x61,
	0x74, 0x61, 0x12, 0x28, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x14, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x41, 0x6e, 0x79, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x16, 0x0a, 0x06,
	0x77, 0x72, 0x69, 0x74, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x77, 0x72,
	0x69, 0x74, 0x65, 0x72, 0x12, 0x38, 0x0a, 0x09, 0x77, 0x72, 0x69, 0x74, 0x65, 0x74, 0x69, 0x6d,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x52, 0x09, 0x77, 0x72, 0x69, 0x74, 0x65, 0x74, 0x69, 0x6d, 0x65, 0x22, 0x1e,
	0x0a, 0x06, 0x51, 0x4d, 0x51, 0x49, 0x6e, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x21,
	0x0a, 0x09, 0x51, 0x4d, 0x51, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x12, 0x14, 0x0a, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x22, 0x40, 0x0a, 0x0c, 0x51, 0x4d, 0x51, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x12, 0x30, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x22, 0x20, 0x0a, 0x08, 0x51, 0x4d, 0x51, 0x46, 0x6c, 0x6f, 0x61, 0x74, 0x12,
	0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x1f, 0x0a, 0x07, 0x51, 0x4d, 0x51, 0x42, 0x6f, 0x6f, 0x6c,
	0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0xaa, 0x01, 0x0a, 0x06, 0x51, 0x4d, 0x51, 0x4c, 0x6f,
	0x67, 0x12, 0x20, 0x0a, 0x0b, 0x61, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x61, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x2a, 0x0a, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x14, 0x2e, 0x71, 0x6d, 0x71, 0x2e, 0x51, 0x4d, 0x51, 0x4c, 0x6f, 0x67, 0x4c,
	0x65, 0x76, 0x65, 0x6c, 0x45, 0x6e, 0x75, 0x6d, 0x52, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x12,
	0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x38, 0x0a, 0x09, 0x74, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54,
	0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x22, 0xb4, 0x01, 0x0a, 0x10, 0x51, 0x4d, 0x51, 0x53, 0x74, 0x72, 0x65, 0x61,
	0x6d, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x12, 0x28, 0x0a, 0x10, 0x6c, 0x61, 0x73, 0x74,
	0x5f, 0x63, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65, 0x64, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0e, 0x6c, 0x61, 0x73, 0x74, 0x43, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65, 0x64,
	0x49, 0x64, 0x12, 0x28, 0x0a, 0x10, 0x6c, 0x61, 0x73, 0x74, 0x5f, 0x70, 0x72, 0x6f, 0x64, 0x75,
	0x63, 0x65, 0x64, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x6c, 0x61,
	0x73, 0x74, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x65, 0x64, 0x49, 0x64, 0x12, 0x25, 0x0a, 0x0e,
	0x74, 0x6f, 0x74, 0x61, 0x6c, 0x5f, 0x63, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65, 0x64, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x0d, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x43, 0x6f, 0x6e, 0x73, 0x75,
	0x6d, 0x65, 0x64, 0x12, 0x25, 0x0a, 0x0e, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x5f, 0x70, 0x72, 0x6f,
	0x64, 0x75, 0x63, 0x65, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0d, 0x74, 0x6f, 0x74,
	0x61, 0x6c, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x65, 0x64, 0x22, 0x4f, 0x0a, 0x09, 0x51, 0x4d,
	0x51, 0x50, 0x72, 0x61, 0x79, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x2e, 0x0a, 0x04, 0x74,
	0x69, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65,
	0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x22, 0x2d, 0x0a, 0x0f, 0x51,
	0x4d, 0x51, 0x41, 0x75, 0x64, 0x69, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a,
	0x0a, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x9c, 0x01, 0x0a, 0x0e, 0x51,
	0x4d, 0x51, 0x4d, 0x71, 0x74, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69, 0x64, 0x12, 0x10, 0x0a,
	0x03, 0x71, 0x6f, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x71, 0x6f, 0x73, 0x12,
	0x14, 0x0a, 0x05, 0x74, 0x6f, 0x70, 0x69, 0x63, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x74, 0x6f, 0x70, 0x69, 0x63, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12,
	0x1a, 0x0a, 0x08, 0x72, 0x65, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x08, 0x72, 0x65, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x64,
	0x75, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09,
	0x64, 0x75, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x65, 0x2a, 0xaa, 0x01, 0x0a, 0x0f, 0x51, 0x4d,
	0x51, 0x4c, 0x6f, 0x67, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x45, 0x6e, 0x75, 0x6d, 0x12, 0x19, 0x0a,
	0x15, 0x4c, 0x4f, 0x47, 0x5f, 0x4c, 0x45, 0x56, 0x45, 0x4c, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45,
	0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x13, 0x0a, 0x0f, 0x4c, 0x4f, 0x47, 0x5f,
	0x4c, 0x45, 0x56, 0x45, 0x4c, 0x5f, 0x54, 0x52, 0x41, 0x43, 0x45, 0x10, 0x01, 0x12, 0x13, 0x0a,
	0x0f, 0x4c, 0x4f, 0x47, 0x5f, 0x4c, 0x45, 0x56, 0x45, 0x4c, 0x5f, 0x44, 0x45, 0x42, 0x55, 0x47,
	0x10, 0x02, 0x12, 0x14, 0x0a, 0x10, 0x4c, 0x4f, 0x47, 0x5f, 0x4c, 0x45, 0x56, 0x45, 0x4c, 0x5f,
	0x41, 0x44, 0x56, 0x49, 0x53, 0x45, 0x10, 0x03, 0x12, 0x12, 0x0a, 0x0e, 0x4c, 0x4f, 0x47, 0x5f,
	0x4c, 0x45, 0x56, 0x45, 0x4c, 0x5f, 0x57, 0x41, 0x52, 0x4e, 0x10, 0x04, 0x12, 0x13, 0x0a, 0x0f,
	0x4c, 0x4f, 0x47, 0x5f, 0x4c, 0x45, 0x56, 0x45, 0x4c, 0x5f, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10,
	0x05, 0x12, 0x13, 0x0a, 0x0f, 0x4c, 0x4f, 0x47, 0x5f, 0x4c, 0x45, 0x56, 0x45, 0x4c, 0x5f, 0x50,
	0x41, 0x4e, 0x49, 0x43, 0x10, 0x06, 0x2a, 0x75, 0x0a, 0x16, 0x51, 0x4d, 0x51, 0x47, 0x61, 0x72,
	0x61, 0x67, 0x65, 0x44, 0x6f, 0x6f, 0x72, 0x53, 0x74, 0x61, 0x74, 0x65, 0x45, 0x6e, 0x75, 0x6d,
	0x12, 0x21, 0x0a, 0x1d, 0x47, 0x41, 0x52, 0x41, 0x47, 0x45, 0x5f, 0x44, 0x4f, 0x4f, 0x52, 0x5f,
	0x53, 0x54, 0x41, 0x54, 0x45, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45,
	0x44, 0x10, 0x00, 0x12, 0x1a, 0x0a, 0x16, 0x47, 0x41, 0x52, 0x41, 0x47, 0x45, 0x5f, 0x44, 0x4f,
	0x4f, 0x52, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x45, 0x5f, 0x4f, 0x50, 0x45, 0x4e, 0x10, 0x01, 0x12,
	0x1c, 0x0a, 0x18, 0x47, 0x41, 0x52, 0x41, 0x47, 0x45, 0x5f, 0x44, 0x4f, 0x4f, 0x52, 0x5f, 0x53,
	0x54, 0x41, 0x54, 0x45, 0x5f, 0x43, 0x4c, 0x4f, 0x53, 0x45, 0x44, 0x10, 0x02, 0x42, 0x09, 0x5a,
	0x07, 0x71, 0x6d, 0x71, 0x2f, 0x71, 0x6d, 0x71, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_src_protobufs_proto_rawDescOnce sync.Once
	file_src_protobufs_proto_rawDescData = file_src_protobufs_proto_rawDesc
)

func file_src_protobufs_proto_rawDescGZIP() []byte {
	file_src_protobufs_proto_rawDescOnce.Do(func() {
		file_src_protobufs_proto_rawDescData = protoimpl.X.CompressGZIP(file_src_protobufs_proto_rawDescData)
	})
	return file_src_protobufs_proto_rawDescData
}

var file_src_protobufs_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_src_protobufs_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_src_protobufs_proto_goTypes = []interface{}{
	(QMQLogLevelEnum)(0),          // 0: qmq.QMQLogLevelEnum
	(QMQGarageDoorStateEnum)(0),   // 1: qmq.QMQGarageDoorStateEnum
	(*QMQData)(nil),               // 2: qmq.QMQData
	(*QMQInt)(nil),                // 3: qmq.QMQInt
	(*QMQString)(nil),             // 4: qmq.QMQString
	(*QMQTimestamp)(nil),          // 5: qmq.QMQTimestamp
	(*QMQFloat)(nil),              // 6: qmq.QMQFloat
	(*QMQBool)(nil),               // 7: qmq.QMQBool
	(*QMQLog)(nil),                // 8: qmq.QMQLog
	(*QMQStreamContext)(nil),      // 9: qmq.QMQStreamContext
	(*QMQPrayer)(nil),             // 10: qmq.QMQPrayer
	(*QMQAudioRequest)(nil),       // 11: qmq.QMQAudioRequest
	(*QMQMqttMessage)(nil),        // 12: qmq.QMQMqttMessage
	(*anypb.Any)(nil),             // 13: google.protobuf.Any
	(*timestamppb.Timestamp)(nil), // 14: google.protobuf.Timestamp
}
var file_src_protobufs_proto_depIdxs = []int32{
	13, // 0: qmq.QMQData.data:type_name -> google.protobuf.Any
	14, // 1: qmq.QMQData.writetime:type_name -> google.protobuf.Timestamp
	14, // 2: qmq.QMQTimestamp.value:type_name -> google.protobuf.Timestamp
	0,  // 3: qmq.QMQLog.level:type_name -> qmq.QMQLogLevelEnum
	14, // 4: qmq.QMQLog.timestamp:type_name -> google.protobuf.Timestamp
	14, // 5: qmq.QMQPrayer.time:type_name -> google.protobuf.Timestamp
	6,  // [6:6] is the sub-list for method output_type
	6,  // [6:6] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_src_protobufs_proto_init() }
func file_src_protobufs_proto_init() {
	if File_src_protobufs_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_src_protobufs_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QMQData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_protobufs_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QMQInt); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_protobufs_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QMQString); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_protobufs_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QMQTimestamp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_protobufs_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QMQFloat); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_protobufs_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QMQBool); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_protobufs_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QMQLog); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_protobufs_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QMQStreamContext); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_protobufs_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QMQPrayer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_protobufs_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QMQAudioRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_protobufs_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QMQMqttMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_src_protobufs_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_src_protobufs_proto_goTypes,
		DependencyIndexes: file_src_protobufs_proto_depIdxs,
		EnumInfos:         file_src_protobufs_proto_enumTypes,
		MessageInfos:      file_src_protobufs_proto_msgTypes,
	}.Build()
	File_src_protobufs_proto = out.File
	file_src_protobufs_proto_rawDesc = nil
	file_src_protobufs_proto_goTypes = nil
	file_src_protobufs_proto_depIdxs = nil
}
