// THIS IS AN AUTOGENERATED FILE... See gen_web_handlers.sh for details.
package qmq

import (
    "net/http"
    "fmt"
)

func Register_web_handler_notification_manager() {

    http.HandleFunc("/js/qmq/notification_manager.js", func(w http.ResponseWriter, r *http.Request) {
        w.Header().Set("Content-Type", "application/javascript")
        fmt.Fprint(w, `class NotificationManager {
    constructor() {
        this._topics = {};
    }

    addListener(topic, listener) {
        if ( !(topic in this._topics) ) {
            this._topics[topic] = [];
        }

        this._topics[topic].push(listener);

        return this;
    }

    notifyListeners(data, context) {
        if (data.key in this._topics) {
            this._topics[data.key].forEach(listener => {
                listener.onNotification(data.key, data, context);
            });
        }
    }

    get topics() {
        return Object.keys(this._topics);
    }
};`)
    })
}
